### ISSUE TITLE
Can you elaborate more related to debugging

### ISSUE THREAD

**Issue by thepenguinthatwants** [Kulak/bawesome#2]
Hi,
I've noticed that there was this part on the tips.
Can you elaborate more related to debug using this notify block? 
```
naughty.notify({
    text = msg .. cmdout .. cmderr,
    timeout = 0, -- don't remove automatically
})
```

**Comment by kulak** [comment]
I agree.  When taken out of context the statment is confusing.

Take a look a this: <https://github.com/Kulak/bawesome/blob/b5b5cd0077c054aca55fbec648718f28530cbb76/b/screenshot.lua>

```lua
function module.exec(cmd, msg)
    awful.spawn.easy_async_with_shell(cmd, function(cmdout, cmderr)
        -- uncomment to debug
        --     naughty.notify({
        --         text = msg .. cmdout .. cmderr,
        --         timeout = 0,
        --     })
    end)
end
```

I need to update the document and either make this complete statement or remove it.
